---
- name: Install required packages
  community.general.pacman:
    name:
      - greetd
      - greetd-regreet
    state: present

- name: Create greeter user
  ansible.builtin.user:
    name: greeter
    shell: "{{ lookup('pipe', 'which bash') }}"

- name: Put regreet config
  ansible.builtin.template:
    src: "regreet.toml.j2"
    dest: "/etc/greetd/regreet.toml"
    mode: '0644'

- name: Hyprland config for regreet
  ansible.builtin.copy:
    src: "hyprland.conf"
    dest: "{{ hypr_config }}"
    mode: '0644'

- name: Greetd config
  ansible.builtin.template:
    src: greetd-config.toml.j2
    dest: /etc/greetd/config.toml

- name: Enable greetd service
  ansible.builtin.systemd_service:
    name: greetd
    state: started
    enabled: yes
