---
- name: Install hyprland and utilities
  community.general.pacman:
    name:
      - linux-headers
      - nvidia-dkms
      - nvidia-utils
      - egl-wayland
      - hyprland
      - hypridle
      - hyprlock
      - hyprsunset
      - hyprpolkitagent
      - brightnessctl
      - xdg-desktop-portal-hyprland
      - xdg-desktop-portal
      - xdg-user-dirs
      - xorg-server-xwayland
      - gnome-keyring
      - wayland-utils
      - wl-clipboard
      - wofi
      - waybar
      - alacritty
      - dolphin
      - impala
      - power-profiles-daemon
      # Login
      - greetd
      - greetd-tuigreet
      # Screenshots
      - grim
      - slurp
    state: present

- name: Greetd config
  ansible.builtin.copy:
    src: greetd-config.toml
    dest: /etc/greetd/config.toml

- name: Enable greetd service
  ansible.builtin.systemd_service:
    name: greetd
    state: started
    enabled: yes

# - name: Enable power-profiles-daemon service
#   become: true
#   become_user: "{{ user }}"
#   ansible.builtin.systemd_service:
#     name: power-profiles-daemon
#     state: started
#     enabled: yes
#     scope: "user"

- name: Hyprland config
  ansible.builtin.template:
    src: "{{ item }}.conf.j2"
    dest: "{{ home_dir }}/.config/hypr/{{ item }}.conf"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0644'
  with_items:
    - hyprland
    - hypridle
    - hyprlock

- name: Ensure users dirs
  become: true
  become_user: "{{ user }}"
  ansible.builtin.command: xdg-user-dirs-update
  args:
    creates: "{{ home_dir }}/Downloads"
