---
- name: Install hyprland and utilities
  community.general.pacman:
    name:
      - alacritty
      - brightnessctl
      - nautilus
      - egl-wayland
      - hypridle
      - hyprland
      - hyprlock
      - hyprpolkitagent
      - hyprsunset
      - impala
      - power-profiles-daemon
      - waybar
      - wayland-utils
      - wl-clipboard
      - wofi
      - xdg-desktop-portal
      - xdg-desktop-portal-hyprland
      - xdg-user-dirs
      - xorg-server-xwayland
      # Login
      - greetd
      - greetd-regreet
      # Screenshots
      - grim
      - slurp
    state: present

- name: Create greeter user
  ansible.builtin.user:
    name: greeter
    shell: "{{ lookup('pipe', 'which bash') }}"

- name: Hyprland config for regreet
  ansible.builtin.copy:
    src: "hyprland.conf"
    dest: "{{ regreet_hypr_config }}"
    mode: '0644'

- name: Greetd config
  ansible.builtin.template:
    src: greetd-config.toml.j2
    dest: /etc/greetd/config.toml

- name: Enable greetd service
  ansible.builtin.systemd_service:
    name: greetd
    state: started
    enabled: yes

- name: Create config directory
  file:
    path: "{{ home_dir }}/.config/hypr"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Hyprland config
  ansible.builtin.template:
    src: "{{ item }}.conf.j2"
    dest: "{{ home_dir }}/.config/hypr/{{ item }}.conf"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0644'
  with_items:
    - hyprland
    - hypridle
    - hyprlock
    - monitors
    - my-programs
    - autostart
    - env-vars
    - permissions
    - look-and-feel
    - input
    - keybindings
    - window-rules
    - workspace-rules

- name: Ensure users dirs
  become: true
  become_user: "{{ user }}"
  ansible.builtin.command: xdg-user-dirs-update
  args:
    creates: "{{ home_dir }}/Downloads"
