---
- name: Install hyprland and utilities
  community.general.pacman:
    name:
      - nvidia-dkms
      - nvidia-utils
      - egl-wayland
      - hyprland
      - xdg-desktop-portal-hyprland
      - xdg-desktop-portal
      - xdg-user-dirs
      - xorg-server-xwayland
      - wayland-utils
      - wl-clipboard
      - wofi
      - foot
      # Fonts
      - noto-fonts
      - ttf-dejavu
      # Login
      - greetd
      - greetd-tuigreet
    state: present

- name: Greetd config
  ansible.builtin.copy:
    src: greetd-config.toml
    dest: /etc/greetd/config.toml

- name: Enable greetd service
  ansible.builtin.systemd_service:
    name: greetd
    state: started
    enabled: yes

- name: Hyprland config
  ansible.builtin.template:
    src: hyprland.conf.j2
    dest: "{{ home_dir }}/.config/hypr/hyprland.conf"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0644'