---
- name: Minimal Linux Setup
  hosts: all
  roles:
    - sudo
    - basic-stuff
    - hyprland
    - bluetooth
    - pipewire
    - printers
    - flatpak-gui-apps
    - oh-my-zsh
    - sublime
    - asdf-vm
    - kubectl
    - wallpapers
