---
- name: Install basic stuff
  community.general.pacman:
    name:
      - ansible
      - autoconf
      - base-devel
      - btop
      - htop
      - curl
      - git
      - gnupg
      - less
      - mc
      - tar
      - unzip
      - vim
      - wget
    state: present

- name: Ensure group "input" exists
  ansible.builtin.group:
    name: "input"
    state: present

- name: Add user to the group to have rights to manage printers
  ansible.builtin.user:
    name: "{{ user }}"
    groups: input
    append: yes
