---
- name: Install basic stuff
  community.general.pacman:
    name:
      - ansible
      - autoconf
      - base-devel
      - curl
      - git
      - gnupg
      - less
      - vim
      - wget
    state: present
