---
- name: Install Bluetooth packages
  community.general.pacman:
    name:
      - bluez
      - bluez-tools
      - blueman
    state: present

- name: Ensure Bluetooth service is running and enabled
  ansible.builtin.service:
    name: bluetooth
    state: started
    enabled: yes
