- name: Install CUPS
  community.general.pacman:
    name:
      - cups
      - cups-pdf
      - cups-filters
      - system-config-printer
    state: present

# - name: Add user to the group to have rights to manage printers
#   ansible.builtin.user:
#     name: "{{ user }}"
#     groups: lpadmin
#     append: yes
