---
- name: Install the package
  ansible.builtin.command: "yay --sync --noconfirm {{ role_name }}"
  args:
    creates: "/usr/bin/{{ role_name }}"

- name: Create config directory
  file:
    path: "{{ config_path | dirname }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"

- name: ashell config
  ansible.builtin.template:
    src: "config.toml.j2"
    dest: "{{ config_path }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0644'
