---
- name: Check if kubectl is installed
  stat:
    path: "/usr/local/bin/kubectl"
  register: kubectl_bin

- name: Get latest stable kubectl version
  when: not kubectl_bin.stat.exists and kubectl_bin.stat.executable
  ansible.builtin.uri:
    url: https://dl.k8s.io/release/stable.txt
    return_content: yes
  register: kubectl_stable_version

- name: Download kubectl binary
  when: not kubectl_stable_version.skipped
  ansible.builtin.get_url:
    mode: '0755'
    dest: "/usr/local/bin/kubectl"
    url: "https://dl.k8s.io/release/{{ kubectl_stable_version.content }}/bin/linux/{{ current_arch }}/kubectl"
    checksum: "sha256:https://dl.k8s.io/release/{{ kubectl_stable_version.content }}/bin/linux/{{ current_arch }}/kubectl.sha256"
