---
- name: Ensure sudo is installed
  community.general.pacman:
    name: sudo
    state: present

- name: Disable root password
  ansible.builtin.user:
    name: root
    password: '!'
    update_password: always

- name: Ensure user is in sudo group
  ansible.builtin.user:
    name: "{{ user }}"
    groups: wheel
    append: yes
