---
- name: Install the package
  community.general.pacman:
    name:
      - waybar

- name: Create config directory
  file:
    path: "{{ home_dir }}/.config/waybar"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"


- name: Put configs
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ home_dir }}/.config/waybar/{{ item }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0644'
  with_items:
    - config
    - style.css
    - power_menu.xml
