---
- name: Install the package
  community.general.pacman:
    name:
      - waybar

- name: Fetch dotfiles from Ja.KooLit
  become: true
  become_user: "{{ user }}"
  ansible.builtin.git:
    repo: 'https://github.com/JaKooLit/Hyprland-Dots.git'
    dest: "{{ jakoolit_hyprland_dots }}"
    update: false

- name: Create a symbolic link
  ansible.builtin.file:
    src: "{{ jakoolit_hyprland_dots }}/config/waybar"
    dest: "{{ home_dir }}/.config/waybar"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link

- name: Link styles
  ansible.builtin.file:
    src: "{{ jakoolit_hyprland_dots }}/config/waybar/style/{{ style }}"
    dest: "{{ jakoolit_hyprland_dots }}/config/waybar/style.css"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link

- name: Link config
  ansible.builtin.file:
    src: "{{ jakoolit_hyprland_dots }}/config/waybar/configs/{{ config }}"
    dest: "{{ jakoolit_hyprland_dots }}/config/waybar/config"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link

- name: Link scrips
  ansible.builtin.file:
    src: "{{ jakoolit_hyprland_dots }}/config/hypr/scripts"
    dest: "{{ home_dir }}/.config/hypr/scrips"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link
