---
- name: Install the package
  community.general.pacman:
    name:
      - wofi

- name: Create config directory
  file:
    path: "{{ home_dir }}/.config/wofi"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"


- name: Put configs
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ home_dir }}/.config/wofi/{{ item }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0644'
  with_items:
    - config
    - omarchy-power-menu.css
