---
- name: Import a gpg key from a url
  community.general.pacman_key:
    id: 1EDDE2CDFC025D17F6DA9EC0ADAE6AD28A8F901A
    url: "https://download.sublimetext.com/sublimehq-pub.gpg"
    state: present

- name: Configure source
  ansible.builtin.blockinfile:
    path: /etc/pacman.conf
    append_newline: true
    prepend_newline: true
    block: |
      [sublime-text]
      Server = https://download.sublimetext.com/arch/stable/x86_64
  register: pacman_conf

- name: Install Sublime
  community.general.pacman:
    name: sublime-text
    state: present
    update_cache: yes
  when: pacman_conf is changed
