---
- name: Install containerd and friends
  community.general.pacman:
    update_cache: yes
    name:
      - docker
      - docker-compose

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ user }}"
    groups: docker
    append: yes
